networks:
  backend:
    driver: bridge

volumes:
  pg_data: null
  rabbitmq: null
  pycache: null

services:
  nginx:
    networks:
      - backend
    ports:
      - ${PORT:-8001}:80
    volumes:
      - ./resources/layout/nginx.conf:/etc/nginx/nginx.conf
      - ./resources/:/usr/share/nginx/html/resources/
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    depends_on:
      - web
  web:
    networks:
      - backend
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
    restart: always
    command: ${COMMAND:-sh ./entrypoint.sh}
    environment:
      - PYTHONPYCACHEPREFIX=/var/cache/pycache
    volumes:
      - .:/code
      - pycache:/var/cache/pycache
    depends_on:
      - db
      - redis
  db:
    networks:
      - backend
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '2309'
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    networks:
      - backend
    restart: always
    image: redis
  rabbitmq:
    networks:
      - backend
    restart: always
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_PASS=2309
      - RABBITMQ_DEFAULT_VHOST=vhost
    volumes:
      - rabbitmq:/var/lib/rabbitmq
